version: '3.4'

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dotabot
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  dota2bot.service:
    image: alr1wn0/dota-telegram-bot:1.0
    restart: always
    environment:
      DB: Server=db;Port=5432;Database=dotastat;User Id=postgres;Password=dotabot;
      STEAM_API_KEY: 522475766263B7CF845BD30EDBAAA5A0
      TELEGRAM_API_KEY: 192156931:AAGZpH3gnDm4cutqSwTtRJ-RpyLqyZJMxtw
    depends_on:
      - db